version: "3"

services:

   local-registry:
     container_name: registry
     image: registry:2.6
     restart: unless-stopped
     volumes:
       - registry-data:/var/lib/registry
     labels:
       - traefik.enable=true
       - traefik.http.routers.registry.service=registry
       - traefik.http.routers.registry.entrypoints=https
       - traefik.http.routers.registry.rule=Host(`registry.lab.lan`)
       - traefik.http.services.registry.loadbalancer.server.port=5000
       - traefik.docker.network=traefik


   reverse-proxy:
     image: traefik:2.10.5
     container_name: traefik-reverse-proxy
     restart: unless-stopped
     command:
       - --api.insecure=true
       - --providers.docker
       - --entrypoints.https.address=:443
       - --entrypoints.https.http.tls=true
       - --entrypoints.registry.address=:5000
       - --log.level=DEBUG
       - --providers.file.directory=/config
       - --providers.file.watch=true
     ports:
       - 80:80
       - 443:443

     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./config/:/config:ro
     secrets:
      - source: traefik.certificate
        target: /certs/registry.lab.lan-crt.pem
      - source: traefik.key
        target: /certs/registry.lab.lan-key.pem



secrets:
  traefik.certificate:
    file: ./secrets/registry.lab.lan-crt.pem
  traefik.key:
    file: ./secrets/registry.lab.lan-key.pem

volumes:
  registry-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data  

networks:
  default:
    name: traefik
